"""materialize re-renders every native surface from the same descriptor (R1)."""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from researchteam import _update_cmd


def _instance(tmp_path: Path, surfaces: tuple[str, ...]) -> Path:
    (tmp_path / "brief.json").write_text(json.dumps({"project_name": "demo", "project_goal": "demo goal"}))
    (tmp_path / ".github" / "agents").mkdir(parents=True)
    for d in surfaces:
        (tmp_path / d / "references").mkdir(parents=True)
        (tmp_path / d / "references" / "build-log.json").write_text("{}")
    return tmp_path


@pytest.fixture
def calls(monkeypatch):
    seen: list[list[str]] = []

    class Done:
        returncode = 0

    monkeypatch.setattr(_update_cmd, "_preflight_agentteams", lambda: "agentteams")
    def fake_run(cmd, cwd=None):
        if "--description" in cmd:
            desc = Path(cwd) / cmd[cmd.index("--description") + 1]
            cmd = cmd + ["#content", desc.read_text()]         # capture before the temp file is removed
        seen.append(cmd)
        return Done()

    monkeypatch.setattr(_update_cmd.subprocess, "run", fake_run)
    monkeypatch.setattr(_update_cmd, "_brief_has_placeholder", lambda root: False)
    import researchteam._personalize as p
    monkeypatch.setattr(p, "is_upstream", lambda root: False)
    monkeypatch.setattr(p, "run_personalize", lambda *a, **k: None)
    return seen


def test_all_native_surfaces_rendered_with_same_descriptor(tmp_path, calls):
    root = _instance(tmp_path, (".claude/agents", ".goose/recipes"))
    (root / ".github/agents/_build-description.json").write_text(
        json.dumps({"selected_archetypes": ["primary-producer", "visual-designer"]}))  # forces roster union
    _update_cmd.run_materialize(root, yes=True, dry_run=False)
    calls[:] = [c for c in calls if "--interop-from" not in c]
    assert len(calls) == 3
    assert "--framework" not in calls[0]                                   # copilot-vscode first
    assert [c[c.index("--framework") + 1] for c in calls[1:]] == ["claude", "goose"]
    assert all("--overwrite" in c and "--materialize-native" in c for c in calls[1:])
    contents = {c[c.index("#content") + 1] for c in calls}
    assert len(contents) == 1 and "visual-designer" in contents.pop()      # same roster on every surface


def test_bare_bridge_dir_is_not_rendered(tmp_path, calls):
    root = _instance(tmp_path, (".claude/agents",))
    (root / ".goose" / "recipes").mkdir(parents=True)                      # no build-log: bridge only
    _update_cmd.run_materialize(root, yes=True, dry_run=False)
    assert [c[c.index("--framework") + 1] for c in calls if "--framework" in c] == ["claude"]


def test_copilot_only_keeps_single_surface(tmp_path, calls):
    root = _instance(tmp_path, (".claude/agents", ".goose/recipes"))
    _update_cmd.run_materialize(root, yes=True, dry_run=False, copilot_only=True)
    assert len(calls) == 1 and "--framework" not in calls[0]


def _renders(calls):
    return [c for c in calls if "--overwrite" in c and "--interop-from" not in c]


def test_adopt_orphans_reaches_every_surface(tmp_path, calls):
    root = _instance(tmp_path, (".claude/agents", ".goose/recipes"))
    _update_cmd.run_materialize(root, yes=True, dry_run=False, adopt_orphans=True)
    assert len(_renders(calls)) == 3 and all("--adopt-orphans" in c for c in _renders(calls))


def test_codex_agents_and_skills_refreshed_when_present(tmp_path, calls):
    root = _instance(tmp_path, (".claude/agents",))
    (root / ".codex" / "agents").mkdir(parents=True)
    (root / ".claude" / "skills").mkdir(parents=True)
    _update_cmd.run_materialize(root, yes=True, dry_run=False)
    interop = [c for c in calls if "--interop-from" in c]
    assert [c[c.index("--interop-from") + 1] for c in interop] == [".github/agents", ".claude/agents"]
    assert all(c[c.index("--framework") + 1] == "codex" for c in interop)
    assert "--interop-skills-only" in interop[1]
    assert all("--overwrite" in c for c in interop)   # otherwise existing projections are skipped
    assert calls.index(interop[0]) > max(calls.index(c) for c in _renders(calls))   # after renders


def test_no_codex_surface_or_opt_out_skips_projection(tmp_path, calls):
    root = _instance(tmp_path, (".claude/agents",))
    _update_cmd.run_materialize(root, yes=True, dry_run=False)             # no .codex dir
    (root / ".codex" / "agents").mkdir(parents=True)
    _update_cmd.run_materialize(root, yes=True, dry_run=False, codex=False)  # opted out
    assert not any("--interop-from" in c for c in calls)


def test_stale_generated_codex_agents_pruned_but_hand_authored_kept(tmp_path, calls):
    root = _instance(tmp_path, ())
    agents = root / ".codex" / "agents"; agents.mkdir(parents=True)
    (root / ".github/agents/kept.agent.md").write_text("x")
    gen = "# Codex custom agent — generated by agentteams from the canonical team.\nname = 'x'\n"
    (agents / "kept.toml").write_text(gen)
    (agents / "retired.toml").write_text(gen)
    (agents / "bespoke.toml").write_text("# hand-authored\nname = 'b'\n")
    _update_cmd.run_materialize(root, yes=True, dry_run=False)
    assert sorted(p.name for p in agents.glob("*.toml")) == ["bespoke.toml", "kept.toml"]


def test_update_layer1_refreshes_codex(tmp_path, calls, monkeypatch):
    root = _instance(tmp_path, ())
    (root / ".codex" / "agents").mkdir(parents=True)
    _update_cmd.run_update(root, ref="main", yes=True, dry_run=False, layer2_only=False, layer1_only=True)
    interop = [c for c in calls if "--interop-from" in c]
    assert interop and all("--overwrite" in c for c in interop)
    merge = [c for c in calls if "--merge" in c]
    assert merge and calls.index(interop[0]) > calls.index(merge[0])


def test_codex_marker_missing_warns(tmp_path, calls, capsys):
    root = _instance(tmp_path, ())
    (root / ".codex" / "agents").mkdir(parents=True)
    _update_cmd._refresh_codex(root, dry_run=False)
    assert "wrote no team marker" in capsys.readouterr().err


def test_codex_marker_present_is_quiet(tmp_path, calls, capsys):
    root = _instance(tmp_path, ())
    refs = root / ".codex" / "agents" / "references"; refs.mkdir(parents=True)
    (refs / "build-log.json").write_text(json.dumps({"origin": "interop"}))
    _update_cmd._refresh_codex(root, dry_run=False)
    assert "team marker" not in capsys.readouterr().err
